services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9081:80"
    depends_on:
      - frontend
      - backend
    networks:
      - internal

  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - SEARX_URL=http://searx:8080
    ports:
      - "9080:8080"
    volumes:
      - ./tmp:/tmp
    depends_on:
      - searx
    networks:
      - internal

  searx:
    image: searxng/searxng:latest
    env_file:
      - .env
    volumes:
      - ./searxng_settings.yml:/etc/searxng/settings.yml:ro
      - ./limiter.toml:/etc/searxng/limiter.toml:ro
    ports:
      - "8081:8080"
    environment:
      - BASE_URL=http://localhost:8081
    networks:
      - internal

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
    ports:
      - "8082:80"
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
